/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easypos;

import DB.MC_DB;
import static easypos.items.jTable1;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.Vector;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hello
 */
public class add_free extends javax.swing.JFrame {

    /**
     * Creates new form add_free
     */
    String s = "";
    private newCashier_test01 newCashier_test01;

    public add_free(newCashier_test01 newCashier_test01) {
        this.newCashier_test01 = newCashier_test01;
        initComponents();
        bend();
    }

    private add_free() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Free Qty");
        setResizable(false);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void bend() {

        Action printAction = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();

            }
        };
        String key = "print";
        jTextField1.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(s).getKeyStroke(KeyEvent.VK_ESCAPE, 0), key);

        jTextField1.getActionMap().put(key, printAction);

    }


    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        if (!jTextField1.getText().trim().isEmpty()) {
            newCashier_test01.s_id = newCashier_test01.s_select_code;
            newCashier_test01.updateType = "Free";
            set_details();
            newCashier_test01.tbUpdate();
            newCashier_test01.getsum();
            newCashier_test01.grab_code();
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Please Enter Free Qty or Press ESC to Exit..");
        }

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void set_details() {
        try {
            ResultSet rs_check = MC_DB.search_dataQuery("SELECT * FROM STOCK WHERE id= '" + newCashier_test01.s_id + "'");
            if (rs_check.first()) {

//                newCashier_test01.s_code = rs_check.getString("code");
//                newCashier_test01.s_name = rs_check.getString("name");
//                newCashier_test01.s_discount = Double.parseDouble(rs_check.getString("sell_price"));
//                newCashier_test01.s_discount_amount = "0";
//                newCashier_test01.d_mrp = Double.parseDouble(rs_check.getString("market_price"));
//                newCashier_test01.d_cost = Double.parseDouble(rs_check.getString("buy_price"));
//                newCashier_test01.d_price = Double.parseDouble(rs_check.getString("sell_price"));
//                newCashier_test01.d_avl_qty = Double.parseDouble(rs_check.getString("qty"));
                newCashier_test01.d_qty = 0.0;
                newCashier_test01.d_free = Double.parseDouble(jTextField1.getText());
//                newCashier_test01.s_sinhala = rs_check.getString("name2");
//                newCashier_test01.s_type = rs_check.getString("type");
//                newCashier_test01.s_warranty = "No";
//                newCashier_test01.d_sub = newCashier_test01.d_qty * newCashier_test01.d_price;
//                newCashier_test01.d_cost_sub = newCashier_test01.d_qty * newCashier_test01.d_cost;

            } else {

            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_free.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_free.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_free.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_free.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_free().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
