/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easypos;

import DB.MC_DB;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Vector;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author hello
 */
public class goods_recieved_note extends javax.swing.JFrame {

    /**
     * Creates new form goods_recieved_note
     */
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String s = "ss";

    public goods_recieved_note() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        fillSupplier();
        GRN_NO();
        Date toDay = new Date();
        dc_date.setDate(toDay);
        dc_exp_date.setDate(toDay);
        menu.add(jPanel8);
        short_fl();
        type_to_rack();
        AutoCompleteDecorator.decorate(combo_supplier);
        short_down_product();
        product_select();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        menu = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combo_supplier = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lbl_grn_no = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_invoice_no = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        combo_grn_type = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        lbl_grn_tot = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_payment = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        lbl_balance = new javax.swing.JLabel();
        myButton5 = new button.MyButton();
        myButton6 = new button.MyButton();
        myButton7 = new button.MyButton();
        myButton8 = new button.MyButton();
        myButton9 = new button.MyButton();
        myButton10 = new button.MyButton();
        myButton11 = new button.MyButton();
        jLabel24 = new javax.swing.JLabel();
        dc_date = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_code = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_s_code = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_brand = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_cost = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_sale = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_mrp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_reorder = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_qty = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_rack = new javax.swing.JTextField();
        combo_type = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        txt_free = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_sinhala = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        dc_exp_date = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        myButton1 = new button.MyButton();
        myButton2 = new button.MyButton();
        myButton4 = new button.MyButton();
        myButton3 = new button.MyButton();
        jLabel22 = new javax.swing.JLabel();
        lbl_avl_qty = new javax.swing.JLabel();

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", ""
            }
        ));
        jTable4.setRowHeight(25);
        jScrollPane4.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(0).setMinWidth(0);
            jTable4.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable4.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable4.getColumnModel().getColumn(2).setMinWidth(200);
            jTable4.getColumnModel().getColumn(2).setPreferredWidth(200);
        }

        jPanel8.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 120));

        menu.setFocusable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Select Supplier :");

        combo_supplier.setEditable(true);
        combo_supplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_supplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        combo_supplier.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_supplierItemStateChanged(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Code", "Name", "Cost"
            }
        ));
        jTable2.setRowHeight(35);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(0);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable2.getColumnModel().getColumn(1).setMinWidth(0);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(0);
            jTable2.getColumnModel().getColumn(1).setMaxWidth(0);
        }

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 0, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Purches History");

        jTable3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable3.setForeground(new java.awt.Color(204, 0, 0));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "GRN No", "Date", "Price"
            }
        ));
        jTable3.setRowHeight(35);
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_supplier, 0, 202, Short.MAX_VALUE))
                    .addComponent(jTextField1)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combo_supplier, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "S Code", "Brand", "Cost", "Sale", "MPR", "Re Order", "Qty", "Free", "UOM", "Rack", "Sub Total", "Sinhala", "Exp Date"
            }
        ));
        jTable1.setRowHeight(35);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setMinWidth(300);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(300);
            jTable1.getColumnModel().getColumn(2).setMinWidth(0);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(3).setMinWidth(0);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(5).setMinWidth(0);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(6).setMinWidth(0);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(7).setMinWidth(0);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(7).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(10).setMinWidth(0);
            jTable1.getColumnModel().getColumn(10).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(10).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(11).setMinWidth(0);
            jTable1.getColumnModel().getColumn(11).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(11).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(13).setMinWidth(0);
            jTable1.getColumnModel().getColumn(13).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(13).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(14).setMinWidth(0);
            jTable1.getColumnModel().getColumn(14).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(14).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-home-24.png"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("GRN NO");

        lbl_grn_no.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_grn_no.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_grn_no.setText("1001");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Invoice No (F1)");

        txt_invoice_no.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_invoice_no.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_invoice_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_invoice_noActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Type :");

        combo_grn_type.setEditable(true);
        combo_grn_type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_grn_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash" }));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("GRN Total");

        lbl_grn_tot.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_grn_tot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_grn_tot.setText("0.00");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Payment");

        txt_payment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_payment.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_payment.setText("0.00");
        txt_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_paymentActionPerformed(evt);
            }
        });
        txt_payment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_paymentKeyReleased(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Balance");

        lbl_balance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_balance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_balance.setText("0.00");

        myButton5.setText("Finished");
        myButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        myButton5.setRadius(9);
        myButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton5ActionPerformed(evt);
            }
        });

        myButton6.setForeground(new java.awt.Color(255, 255, 255));
        myButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-product-32.png"))); // NOI18N
        myButton6.setText("Stock");
        myButton6.setToolTipText("Stock");
        myButton6.setColor(new java.awt.Color(0, 0, 102));
        myButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myButton6.setRadius(9);
        myButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton6ActionPerformed(evt);
            }
        });

        myButton7.setForeground(new java.awt.Color(255, 255, 255));
        myButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-supplier-32.png"))); // NOI18N
        myButton7.setText("Supplier");
        myButton7.setToolTipText("Supplier");
        myButton7.setColor(new java.awt.Color(0, 0, 102));
        myButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myButton7.setRadius(9);
        myButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton7ActionPerformed(evt);
            }
        });

        myButton8.setForeground(new java.awt.Color(255, 255, 255));
        myButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-invoice-32.png"))); // NOI18N
        myButton8.setText("Invoice");
        myButton8.setToolTipText("Invoice");
        myButton8.setColor(new java.awt.Color(0, 0, 102));
        myButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myButton8.setRadius(9);
        myButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton8ActionPerformed(evt);
            }
        });

        myButton9.setForeground(new java.awt.Color(255, 255, 255));
        myButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-procurement-32.png"))); // NOI18N
        myButton9.setText("Purchase");
        myButton9.setToolTipText("Purchase");
        myButton9.setColor(new java.awt.Color(0, 0, 102));
        myButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myButton9.setRadius(9);
        myButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton9ActionPerformed(evt);
            }
        });

        myButton10.setForeground(new java.awt.Color(255, 255, 255));
        myButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-do-not-mix-32.png"))); // NOI18N
        myButton10.setText("Orders");
        myButton10.setToolTipText("Orders");
        myButton10.setColor(new java.awt.Color(0, 0, 102));
        myButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton10ActionPerformed(evt);
            }
        });

        myButton11.setForeground(new java.awt.Color(255, 255, 255));
        myButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-expired-32.png"))); // NOI18N
        myButton11.setText("Expired");
        myButton11.setToolTipText("Expired");
        myButton11.setColor(new java.awt.Color(0, 0, 102));
        myButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton11ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Date :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_grn_no, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(myButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_balance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_payment, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_grn_tot, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(myButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(myButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(0, 0, 0)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(myButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(myButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(1, 1, 1)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(myButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(myButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_invoice_no)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dc_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(combo_grn_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_grn_no, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_invoice_no, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_grn_type, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dc_date, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_grn_tot, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_balance, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(myButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(myButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(myButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Code :");

        txt_code.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codeActionPerformed(evt);
            }
        });
        txt_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_codeKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Name :");

        txt_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("G. Name :");

        txt_s_code.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_s_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_s_codeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Brand :");

        txt_brand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_brandActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Cost :");

        txt_cost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_costActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Sale:");

        txt_sale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_saleActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("MRP :");

        txt_mrp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_mrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mrpActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Re Order :");

        txt_reorder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_reorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_reorderActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Qty :");

        txt_qty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qtyActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("UOM :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Rack :");

        txt_rack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_rack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rackActionPerformed(evt);
            }
        });

        combo_type.setEditable(true);
        combo_type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Units", "Gram", "Pieces", "Box", "Case", "Kg", "Litre", "M", "Bottle", "Inch", "Feet", "none" }));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Free :");

        txt_free.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_free.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_freeActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("S. Name :");

        txt_sinhala.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        txt_sinhala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sinhalaActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("EXP :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_code)
                    .addComponent(txt_sinhala)
                    .addComponent(txt_brand)
                    .addComponent(txt_free)
                    .addComponent(txt_reorder)
                    .addComponent(combo_type, 0, 1, Short.MAX_VALUE)
                    .addComponent(txt_sale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dc_exp_date, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txt_rack)
                    .addComponent(txt_name)
                    .addComponent(txt_s_code)
                    .addComponent(txt_cost)
                    .addComponent(txt_mrp)
                    .addComponent(txt_qty))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_code, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sinhala, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_s_code)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_brand, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_cost)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_sale, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mrp)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_reorder, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10)
                    .addComponent(txt_qty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_type, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_rack, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_free, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dc_exp_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        myButton1.setForeground(new java.awt.Color(255, 255, 255));
        myButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-40.png"))); // NOI18N
        myButton1.setText("Add");
        myButton1.setColor(new java.awt.Color(0, 0, 102));
        myButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        myButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myButton1.setRadius(25);
        myButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });

        myButton2.setForeground(new java.awt.Color(255, 255, 255));
        myButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-edit-row-40.png"))); // NOI18N
        myButton2.setText("Edit");
        myButton2.setColor(new java.awt.Color(0, 0, 102));
        myButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        myButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myButton2.setRadius(25);
        myButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });

        myButton4.setBackground(new java.awt.Color(0, 0, 102));
        myButton4.setForeground(new java.awt.Color(255, 255, 255));
        myButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-clear-40.png"))); // NOI18N
        myButton4.setText("Clear");
        myButton4.setColor(new java.awt.Color(0, 0, 102));
        myButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        myButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myButton4.setRadius(25);
        myButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton4ActionPerformed(evt);
            }
        });

        myButton3.setForeground(new java.awt.Color(255, 255, 255));
        myButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-remove-40.png"))); // NOI18N
        myButton3.setText("Remove");
        myButton3.setColor(new java.awt.Color(0, 0, 102));
        myButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        myButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myButton3.setRadius(25);
        myButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton3ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("AVL Qty :");

        lbl_avl_qty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_avl_qty.setForeground(new java.awt.Color(204, 0, 0));
        lbl_avl_qty.setText("0.00");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(myButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(myButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(myButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                    .addComponent(lbl_avl_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(myButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(myButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(myButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(myButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_avl_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void product_select() {
        jTable4.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent evt) {

                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    String s_item_id = jTable4.getValueAt(jTable4.getSelectedRow(), 0).toString();
                    String s_item_code = jTable4.getValueAt(jTable4.getSelectedRow(), 1).toString();
                    loadItems(s_item_id);
                    find_item_history(s_item_code);
                    menu.setVisible(false);
                }
            }

        });

    }

    public void short_down_product() {
        txt_code.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                    jTable4.grabFocus();
                    jTable4.setRowSelectionInterval(0, 0);

                }
            }
        });

    }

    public void type_to_rack() {
        combo_type.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    txt_rack.grabFocus();
                }
            }
        });

    }

    public void short_fl() {

        Action printAction = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {
                txt_invoice_no.grabFocus();
                txt_invoice_no.selectAll();
            }
        };
        String key = "print";
        txt_invoice_no.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(s).getKeyStroke(KeyEvent.VK_F1, 0), key);

        txt_invoice_no.getActionMap().put(key, printAction);

    }

    private void GRN_NO() {

        try {
            ResultSet rs = MC_DB.search_dataQuery("select max(grn_no) from grn_details");
            if (rs.first()) {
                if (rs.getString(1) != null) {
                    int i = Integer.parseInt(rs.getString(1));
                    lbl_grn_no.setText(i + 1 + "");
                } else {
                    lbl_grn_no.setText("1001");
                }

            } else {
                lbl_grn_no.setText("1001");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }finally{
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
            e.printStackTrace();
            }
        }
    }

    private void fillSupplier() {

        try {
            ResultSet rs = MC_DB.search_dataQuery("select * from supplier ");

            while (rs.next()) {
                String barcode = rs.getString("name");
                combo_supplier.addItem(barcode);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }finally{
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
            e.printStackTrace();
            }
        }
    }

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        saveTemp();
    }//GEN-LAST:event_myButton1ActionPerformed

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();

        String r = dt.getValueAt(jTable1.getSelectedRow(), 0).toString();

        //remove product
        int rw = jTable1.getSelectedRow();
        dt.removeRow(rw);
        saveTemp();

    }//GEN-LAST:event_myButton2ActionPerformed

    private void myButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton4ActionPerformed

        clear_tf();
    }//GEN-LAST:event_myButton4ActionPerformed

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();

        String r = dt.getValueAt(jTable1.getSelectedRow(), 0).toString();

        //remove product
        int rw = jTable1.getSelectedRow();
        dt.removeRow(rw);
        clear_tf();
    }//GEN-LAST:event_myButton3ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        new Dashboard_001().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void combo_supplierItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_supplierItemStateChanged
        s_supplier = combo_supplier.getSelectedItem().toString();
        loadTable(s_supplier);
    }//GEN-LAST:event_combo_supplierItemStateChanged

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        String key = "%" + jTextField1.getText().trim() + "%";
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            dtm.setRowCount(0);
            ResultSet rs = MC_DB.search_dataQuery("SELECT * FROM stock WHERE supplier = '" + s_supplier + "' AND (code LIKE '" + key + "' OR name LIKE '" + key + "')");
            NumberFormat numberFormat = new DecimalFormat("#,##0.00");

            while (rs.next()) {
                Vector v = new Vector();

                v.add(rs.getString("id"));
                v.add(rs.getString("code"));
                v.add(rs.getString("name"));
                v.add(numberFormat.format(rs.getDouble("buy_price")));

                dtm.addRow(v);
            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        String s_item_id = jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString();
        String s_item_code = jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString();
        loadItems(s_item_id);
        find_item_history(s_item_code);
    }//GEN-LAST:event_jTable2MousePressed

    private void txt_rackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rackActionPerformed
        txt_free.grabFocus();
        txt_free.setText("0");
        txt_free.selectAll();
    }//GEN-LAST:event_txt_rackActionPerformed

    private void txt_freeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_freeActionPerformed
        saveTemp();            
      
    }//GEN-LAST:event_txt_freeActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        s_code = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        s_name = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        s_scode = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
        s_brand = jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
        s_cost = jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString();
        s_sale = jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString();
        s_mrp = jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString();
        s_reorder = jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString();
        s_qty = jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString();
        s_free = jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString();
        s_type = jTable1.getValueAt(jTable1.getSelectedRow(), 10).toString();
        s_rack = jTable1.getValueAt(jTable1.getSelectedRow(), 11).toString();

        txt_brand.setText(s_brand);
        txt_code.setText(s_code);
        txt_cost.setText(s_cost);
        txt_free.setText(s_free);
        txt_mrp.setText(s_mrp);
        txt_name.setText(s_name);
        txt_qty.setText(s_qty);
        txt_rack.setText(s_rack);
        txt_reorder.setText(s_reorder);
        txt_s_code.setText(s_scode);
        txt_sale.setText(s_sale);
    }//GEN-LAST:event_jTable1MousePressed

    private void myButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton5ActionPerformed
        GRN_NO();
        save_grn_details();
        save_items_details();
        checkCredit();
        GRN_NO();
        clear_tf();
        clear_details();
    }//GEN-LAST:event_myButton5ActionPerformed

    private void txt_paymentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_paymentKeyReleased
        if (!txt_payment.getText().trim().isEmpty()) {
            double tot = Double.parseDouble(lbl_grn_tot.getText().trim().replace(",", ""));
            double payment = Double.parseDouble(txt_payment.getText().trim().replace(",", ""));
            double balance = tot - payment;

            lbl_balance.setText(new DecimalFormat("#,##0.00").format(balance));
        } else {
            lbl_balance.setText("0.00");
        }
    }//GEN-LAST:event_txt_paymentKeyReleased

    private void txt_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codeActionPerformed
        txt_name.grabFocus();
    }//GEN-LAST:event_txt_codeActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        txt_sinhala.grabFocus();
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_s_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_s_codeActionPerformed
        txt_brand.grabFocus();
    }//GEN-LAST:event_txt_s_codeActionPerformed

    private void txt_brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_brandActionPerformed
        txt_cost.grabFocus();
    }//GEN-LAST:event_txt_brandActionPerformed

    private void txt_costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_costActionPerformed
        txt_sale.grabFocus();
    }//GEN-LAST:event_txt_costActionPerformed

    private void txt_saleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_saleActionPerformed
        txt_mrp.grabFocus();
    }//GEN-LAST:event_txt_saleActionPerformed

    private void txt_mrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mrpActionPerformed
        txt_reorder.grabFocus();
    }//GEN-LAST:event_txt_mrpActionPerformed

    private void txt_reorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_reorderActionPerformed
        txt_qty.grabFocus();
    }//GEN-LAST:event_txt_reorderActionPerformed

    private void txt_qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qtyActionPerformed
        combo_type.grabFocus();
    }//GEN-LAST:event_txt_qtyActionPerformed

    private void txt_sinhalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sinhalaActionPerformed
        txt_s_code.grabFocus();
    }//GEN-LAST:event_txt_sinhalaActionPerformed

    private void txt_invoice_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_invoice_noActionPerformed
        txt_payment.grabFocus();
        txt_payment.selectAll();
    }//GEN-LAST:event_txt_invoice_noActionPerformed

    private void txt_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_paymentActionPerformed
        myButton5ActionPerformed(evt);
    }//GEN-LAST:event_txt_paymentActionPerformed

    private void txt_codeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codeKeyReleased
        if (txt_code.getText().isEmpty()) {
            menu.setVisible(false);
        } else {

            menu.show(txt_code, 0, txt_code.getHeight());

            String key = txt_code.getText().trim() + "%";
            try {
                DefaultTableModel dtm = (DefaultTableModel) jTable4.getModel();
                dtm.setRowCount(0);
                ResultSet rs = MC_DB.search_dataQuery("SELECT * FROM stock WHERE code like '" + key + "' or name like '" + key + "' or s_code like '" + key + "' ");
                while (rs.next()) {

                    Vector v = new Vector();

                    v.add(rs.getString("id"));
                    v.add(rs.getString("code"));
                    v.add(rs.getString("name"));
                    v.add(rs.getString("sell_price"));

                    dtm.addRow(v);

                }

            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    MC_DB.myConnection().close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
//     jTextField2.grabFocus();
            menu.setVisible(false);

        }
    }//GEN-LAST:event_txt_codeKeyReleased

    private void myButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton6ActionPerformed
        new product_list().setVisible(true);
    }//GEN-LAST:event_myButton6ActionPerformed

    private void myButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton7ActionPerformed
        new supplier_list().setVisible(true);
    }//GEN-LAST:event_myButton7ActionPerformed

    private void myButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton8ActionPerformed
        new newCashier_test01().setVisible(true);
    }//GEN-LAST:event_myButton8ActionPerformed

    private void myButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton9ActionPerformed
        new purchesList().setVisible(true);
    }//GEN-LAST:event_myButton9ActionPerformed

    private void myButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton10ActionPerformed
        new order_list().setVisible(true);
    }//GEN-LAST:event_myButton10ActionPerformed

    private void myButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton11ActionPerformed
        new exp_item().setVisible(true);
    }//GEN-LAST:event_myButton11ActionPerformed

    String s_supplier, s_name, s_code, s_qty, s_price, s_sub, s_cost, s_warranty, s_dis,
            s_serialNo, s_scode, s_brand, s_sale, s_mrp, s_reorder, s_type, s_rack, s_free, s_sinhala, s_exp_date;
    Double d_qty, d_price, d_cost, d_sub, d_cost_sub, d_dis, d_price2, d_cal;

    public void saveTemp() {
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        s_code = txt_code.getText().trim();
        s_name = txt_name.getText().trim();
        s_scode = txt_s_code.getText().trim();
        s_brand = txt_brand.getText().trim();

        s_reorder = txt_reorder.getText().trim();
        s_qty = txt_qty.getText().trim();
        s_type = combo_type.getSelectedItem().toString();
        s_rack = txt_rack.getText().trim();
        s_free = txt_free.getText().trim();
        s_sinhala = txt_sinhala.getText().trim();
        s_exp_date = sdf.format(dc_exp_date.getDate());

        s_qty = txt_qty.getText().trim();
        s_cost = String.format("%.2f", Double.parseDouble(txt_cost.getText().trim()));
        s_mrp = String.format("%.2f", Double.parseDouble(txt_mrp.getText().trim()));
        s_sale = String.format("%.2f", Double.parseDouble(txt_sale.getText().trim()));

        d_qty = Double.parseDouble(txt_qty.getText().trim());
        d_cost = Double.parseDouble(txt_cost.getText().trim());
        d_cost_sub = d_qty * d_cost;

        Vector v = new Vector();

        v.add(s_code);
        v.add(s_name);
        v.add(s_scode);
        v.add(s_brand);
        v.add(s_cost);
        v.add(s_sale);
        v.add(s_mrp);
        v.add(s_reorder);
        v.add(s_qty);
        v.add(s_free);
        v.add(s_type);
        v.add(s_rack);
        v.add(String.format("%.2f", d_cost_sub));
        v.add(s_sinhala);
        v.add(s_exp_date);
    
        dt.addRow(v);
        

        int lastRow = jTable1.getRowCount() - 1;

        if (lastRow >= 0) {
            jTable1.setRowSelectionInterval(lastRow, lastRow);
            jTable1.scrollRectToVisible(jTable1.getCellRect(lastRow, 0, true));
        }
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
            jTable1.getColumnModel().getColumn(9).setCellRenderer(rightRenderer);
            jTable1.getColumnModel().getColumn(8).setCellRenderer(rightRenderer);
            jTable1.getColumnModel().getColumn(12).setCellRenderer(rightRenderer);
        }
        clear_tf();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(goods_recieved_note.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(goods_recieved_note.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(goods_recieved_note.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(goods_recieved_note.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new goods_recieved_note().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_grn_type;
    private javax.swing.JComboBox<String> combo_supplier;
    private javax.swing.JComboBox<String> combo_type;
    private com.toedter.calendar.JDateChooser dc_date;
    private com.toedter.calendar.JDateChooser dc_exp_date;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_avl_qty;
    private javax.swing.JLabel lbl_balance;
    private javax.swing.JLabel lbl_grn_no;
    private javax.swing.JLabel lbl_grn_tot;
    private javax.swing.JPopupMenu menu;
    private button.MyButton myButton1;
    private button.MyButton myButton10;
    private button.MyButton myButton11;
    private button.MyButton myButton2;
    private button.MyButton myButton3;
    private button.MyButton myButton4;
    private button.MyButton myButton5;
    private button.MyButton myButton6;
    private button.MyButton myButton7;
    private button.MyButton myButton8;
    private button.MyButton myButton9;
    private javax.swing.JTextField txt_brand;
    private javax.swing.JTextField txt_code;
    private javax.swing.JTextField txt_cost;
    private javax.swing.JTextField txt_free;
    private javax.swing.JTextField txt_invoice_no;
    private javax.swing.JTextField txt_mrp;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_payment;
    private javax.swing.JTextField txt_qty;
    private javax.swing.JTextField txt_rack;
    private javax.swing.JTextField txt_reorder;
    private javax.swing.JTextField txt_s_code;
    private javax.swing.JTextField txt_sale;
    private javax.swing.JTextField txt_sinhala;
    // End of variables declaration//GEN-END:variables

    private void loadTable(String s_supplier) {
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            dtm.setRowCount(0);
            ResultSet rs = MC_DB.search_dataQuery("SELECT * FROM stock WHERE supplier = '" + s_supplier + "'");
            NumberFormat numberFormat = new DecimalFormat("#,##0.00");
            while (rs.next()) {

                Vector v = new Vector();

                v.add(rs.getString("id"));
                v.add(rs.getString("code"));
                v.add(rs.getString("name"));
                v.add(numberFormat.format(rs.getDouble("buy_price")));

                dtm.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void loadItems(String s_item_id) {
        try {
            ResultSet rs_stock = MC_DB.search_dataQuery("SELECT * FROM stock WHERE id = '" + s_item_id + "'");
            if (rs_stock.next()) {
                txt_brand.setText(rs_stock.getString("brand"));
                txt_code.setText(rs_stock.getString("code"));
                txt_cost.setText(rs_stock.getString("buy_price"));
                txt_mrp.setText(rs_stock.getString("market_price"));
                txt_name.setText(rs_stock.getString("name"));
                lbl_avl_qty.setText(rs_stock.getString("qty"));
                txt_rack.setText(rs_stock.getString("rack"));
                txt_reorder.setText(rs_stock.getString("reorder"));
                txt_s_code.setText(rs_stock.getString("s_code"));
                txt_sale.setText(rs_stock.getString("sell_price"));
                txt_sinhala.setText(rs_stock.getString("name2"));
                combo_type.setSelectedItem(rs_stock.getString("type"));
                combo_supplier.setSelectedItem(rs_stock.getString("supplier"));
                txt_qty.setText("1");
                txt_qty.selectAll();
                txt_qty.grabFocus();
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void getsum() {

        double sum = 0;

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 12).toString());
        }

        lbl_grn_tot.setText(new DecimalFormat("#,##0.00").format(sum));

//        qtys();
    }

    private void clear_tf() {
        txt_code.setText("");
        txt_name.setText("");
        txt_brand.setText("");
        txt_cost.setText("");
        txt_mrp.setText("");
        txt_qty.setText("");
        txt_rack.setText("");
        txt_reorder.setText("");
        txt_s_code.setText("");
        txt_sale.setText("");
        txt_free.setText("");
        txt_sinhala.setText("");
        lbl_avl_qty.setText("");
        txt_code.grabFocus();

        getsum();
    }
    String s_grn_no, s_invo_no, s_grn_type, s_total, s_payment, s_balance, s_date, s_time, s_user, s_data, s_colomn;

    private void save_grn_details() {
        try {

            s_grn_no = lbl_grn_no.getText().trim();
            s_supplier = combo_supplier.getSelectedItem().toString();
            s_date = sdf.format(dc_date.getDate());
            s_invo_no = txt_invoice_no.getText().trim();
            s_grn_type = combo_grn_type.getSelectedItem().toString();
            s_total = lbl_grn_tot.getText().trim().replace(",", "");
            s_payment = txt_payment.getText().trim();
            s_balance = lbl_balance.getText().trim().replace(",", "");
            s_date = sdf.format(dc_date.getDate());
            LocalTime time = LocalTime.now();
            DateTimeFormatter dtf3 = DateTimeFormatter.ofPattern("hh:mm:ss a");
            String time1 = time.format(dtf3);
            s_user = login.log;

            s_colomn = "grn_no,supplier,invo_no,type,grn_tot,payment,balance,date,time,user";
            s_data = " '" + s_grn_no + "','" + s_supplier + "','" + s_invo_no + "','" + s_grn_type + "',"
                    + "'" + s_total + "','" + s_payment + "','" + s_balance + "','" + s_date + "',"
                    + "'" + time1 + "','" + s_user + "' ";

            MC_DB.add_data_WithColumns("grn_details", s_colomn, s_data);

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }

    private void save_items_details() {
        try {

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            for (int i = 0; i < dtm.getRowCount(); i++) {
                System.out.println(i);
                s_code = dtm.getValueAt(i, 0).toString();
                s_name = dtm.getValueAt(i, 1).toString();
                s_scode = dtm.getValueAt(i, 2).toString();
                s_brand = dtm.getValueAt(i, 3).toString();
                s_cost = dtm.getValueAt(i, 4).toString();
                s_sale = dtm.getValueAt(i, 5).toString();
                s_mrp = dtm.getValueAt(i, 6).toString();
                s_reorder = dtm.getValueAt(i, 7).toString();
                s_qty = dtm.getValueAt(i, 8).toString();
                s_free = dtm.getValueAt(i, 9).toString();
                s_type = dtm.getValueAt(i, 10).toString();
                s_rack = dtm.getValueAt(i, 11).toString();
                s_sub = dtm.getValueAt(i, 12).toString();
                s_sinhala = dtm.getValueAt(i, 13).toString();
                s_exp_date = dtm.getValueAt(i, 14).toString();
                s_grn_no = lbl_grn_no.getText().trim();

                if (s_reorder.equals("")) {
                    s_reorder = "0";
                }
                if (s_free.equals("")) {
                    s_free = "0";
                }

                try {
                s_colomn = "code,name,s_code,brand,cost,mrp,sale,re_order,qty,free,type,rack,sub,grn_no,sinhala_name,exp_date";
                s_data = " '" + s_code + "','" + s_name + "','" + s_scode + "','" + s_brand + "',"
                        + "'" + s_cost + "','" + s_mrp + "','" + s_sale + "','" + s_reorder + "',"
                        + "'" + s_qty + "','" + s_free + "','" + s_type + "','" + s_rack + "',"
                        + "'" + s_sub + "','" + s_grn_no + "','" + s_sinhala + "','" + s_exp_date + "' ";

                MC_DB.add_data_WithColumns("grn_item_details", s_colomn, s_data);
                    
                ResultSet rs_stock = MC_DB.search_dataQuery("SELECT * FROM stock WHERE code = '" + s_code + "' && buy_price = '" + s_cost + "'");
                if (rs_stock.next()) {
                    MC_DB.insert_data("UPDATE stock SET qty = qty + '" + s_qty + "', qty = qty+'" + s_free + "' "
                            + "WHERE code = '" + s_code + "' && buy_price = '" + s_cost + "'");
                } else {
                    MC_DB.insert_data("INSERT INTO stock(code,name,s_code,brand,supplier,buy_price,market_price,sell_price,rack,reorder,expire_date,qty,type,name2)"
                            + "VALUES('" + s_code + "','" + s_name + "','" + s_scode + "','" + s_brand + "','" + s_supplier + "','" + s_cost + "','" + s_mrp + "','" + s_sale + "','" + s_rack + "','" + s_reorder + "','" + s_exp_date + "','" + s_qty + "','" + s_type + "','" + s_sinhala + "')");
                    MC_DB.insert_data("UPDATE stock SET qty = qty + '" + s_free + "' WHERE code = '" + s_code + "' && buy_price = '" + s_cost + "'");

                }
                } catch (Exception e) {
                e.printStackTrace();
                }finally{
                    try {
                        MC_DB.myConnection().close();
                    } catch (Exception e) {
                    e.printStackTrace();
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }finally{
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
            e.printStackTrace();
            }
        }
    }

    private void find_item_history(String s_item_code) {
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable3.getModel();
            dtm.setRowCount(0);
            DecimalFormat df = new DecimalFormat("#,##0.00");
            ResultSet rs = MC_DB.search_dataQuery("SELECT * FROM grn_details LEFT "
                    + "JOIN grn_item_details ON grn_details.grn_no = grn_item_details.grn_no "
                    + "WHERE grn_item_details.code = '" + s_item_code + "' ORDER BY grn_details.grn_no DESC");

            while (rs.next()) {
                Vector<String> row = new Vector<>();
                row.add(rs.getString("grn_details.grn_no"));
                row.add(rs.getString("grn_details.date"));
                double cost = rs.getDouble("grn_item_details.cost");
                String formattedCost = df.format(cost);
                row.add(formattedCost);

                dtm.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void clear_details() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel dtm1 = (DefaultTableModel) jTable2.getModel();
        DefaultTableModel dtm2 = (DefaultTableModel) jTable3.getModel();

        dtm.setRowCount(0);
        dtm1.setRowCount(0);
        dtm2.setRowCount(0);
        GRN_NO();
        txt_invoice_no.setText("");
        txt_payment.setText("0.00");
        getsum();
        combo_supplier.setSelectedItem("");

    }

    private void checkCredit() {
        s_supplier = combo_supplier.getSelectedItem().toString();
        s_balance = lbl_balance.getText().trim().replace(",", "").replace("-", "");
        
        try {
            if (combo_grn_type.getSelectedItem().toString().equals("Credit")) {
                System.out.println("if athule");
                MC_DB.insert_data("UPDATE supplier SET credit_amount = credit_amount + '" + s_balance + "' WHERE name = '" + s_supplier + "'");
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

}
