/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easypos;

import DB.MC_DB;
import static easypos.newCashier_test01.s_price_type;
import static easypos.newCashier_test01.s_throw_item_id;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class items extends javax.swing.JFrame {

    /**
     * Creates new form items
     */
    private newCashier_test01 newCashier_test01;

    public items(newCashier_test01 newCashier_test01) {
        this.newCashier_test01 = newCashier_test01;
        initComponents();
        set_items();
    }

    private items() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Item");
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 330));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            if (jTable1.getRowCount() > 0) {
                String id = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
                newCashier_test01.s_id = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
                newCashier_test01.find_product(id);
                this.dispose();
            }

    }//GEN-LAST:event_jTable1KeyPressed
    }

    private void set_details(String s_id) {
        try {
            ResultSet rs_check = MC_DB.search_dataQuery("SELECT * FROM STOCK WHERE id= '" + s_id + "'");
            if (rs_check.first()) {

                newCashier_test01.s_code = rs_check.getString("code");
                newCashier_test01.s_name = rs_check.getString("name");
                newCashier_test01.s_discount_amount = "0";
                newCashier_test01.d_mrp = Double.parseDouble(rs_check.getString("market_price"));
                newCashier_test01.d_cost = Double.parseDouble(rs_check.getString("buy_price"));

                if (s_price_type.equals("Retail")) {
                    newCashier_test01.d_price = Double.parseDouble(rs_check.getString("sell_price"));
                    newCashier_test01.s_discount = Double.parseDouble(rs_check.getString("sell_price"));
                } else if (s_price_type.equals("Wholesale")) {
                    newCashier_test01.d_price = Double.parseDouble(rs_check.getString("wholesale"));
                    newCashier_test01.s_discount = Double.parseDouble(rs_check.getString("wholesale"));
                } else if (s_price_type.equals("P1")) {
                    newCashier_test01.d_price = Double.parseDouble(rs_check.getString("wholesale"));
                    newCashier_test01.s_discount = Double.parseDouble(rs_check.getString("wholesale"));

                } else if (s_price_type.equals("P2")) {
                    newCashier_test01.d_price = Double.parseDouble(rs_check.getString("wholesale"));
                    newCashier_test01.s_discount = Double.parseDouble(rs_check.getString("wholesale"));

                } else if (s_price_type.equals("P3")) {
                    newCashier_test01.d_price = Double.parseDouble(rs_check.getString("wholesale"));
                    newCashier_test01.s_discount = Double.parseDouble(rs_check.getString("wholesale"));
                }

                newCashier_test01.d_avl_qty = Double.parseDouble(rs_check.getString("qty"));
                newCashier_test01.d_qty = 1.0;
                newCashier_test01.d_free = 0.0;
                newCashier_test01.s_sinhala = rs_check.getString("name2");
                newCashier_test01.s_type = rs_check.getString("type");
                newCashier_test01.s_warranty = "No";
                newCashier_test01.d_sub = newCashier_test01.d_qty * newCashier_test01.d_price;
                newCashier_test01.d_cost_sub = newCashier_test01.d_qty * newCashier_test01.d_cost;
                newCashier_test01.tbUpdate();

                newCashier_test01.getsum();
                newCashier_test01.grab_code();
                this.dispose();

            } else {

            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public void set_items() {

        String code = newCashier_test01.s_throw_item_id;
        try {
            jTable1.grabFocus();
            jTable1.setRowSelectionInterval(0, 0);
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            ResultSet rs = MC_DB.search_dataQuery("SELECT * FROM stock WHERE code = '" + code + "'");
            while (rs.next()) {

                Vector v = new Vector();

                v.add(rs.getString("id"));
                v.add(rs.getString("name"));
                v.add(rs.getString("sell_price"));
                dtm.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new items().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
