/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easypos;

import DB.MC_DB;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Vector;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hello
 */
public class product_list extends javax.swing.JFrame {

    /**
     * Creates new form product_list
     */
    String s="";
    public product_list(JPanel jPanel1, JScrollPane jScrollPane1, JTable jTable1, JTextField jTextField1) throws HeadlessException {
        this.jPanel1 = jPanel1;
        this.jScrollPane1 = jScrollPane1;
        this.jTable1 = jTable1;
        this.jTextField1 = jTextField1;
    }

    public product_list() {
        initComponents();
        tbups();
        bend();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LookUp");
        setResizable(false);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Code", "Name", "MRP", "Sale", "Price 001", "Price 002", "Price 003", "Qty", "Re Order", "Rack"
            }
        ));
        jTable1.setRowHeight(35);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(1).setMinWidth(150);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(150);
            jTable1.getColumnModel().getColumn(2).setMinWidth(300);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(300);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Press ESC to Exit.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void bend() {

        Action printAction = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {
               dispose();
              
            }
        };
        String key = "print";
        jTextField1.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(s).getKeyStroke(KeyEvent.VK_ESCAPE, 0), key);

        jTextField1.getActionMap().put(key, printAction);

    }
    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        try {
                String key = "%" + jTextField1.getText() + "%";

         
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
           ResultSet rs = MC_DB.search_dataQuery("SELECT * FROM stock WHERE type like '" + key + "' or reorder like '" + key + "' or rack like '" + key + "' or code like '" + key + "' or name like '" + key + "' or brand like '" + key + "' or s_code like '" + key + "' or supplier like '" + key + "'");
            NumberFormat numberFormat = new DecimalFormat("#,##0.00");
            while (rs.next()) {

                Vector v = new Vector();

                v.add(rs.getString("id"));
                v.add(rs.getString("code"));
                v.add(rs.getString("name"));
                v.add(numberFormat.format(rs.getDouble("sell_price")));
                v.add(numberFormat.format(rs.getDouble("qty")));
                v.add(numberFormat.format(rs.getDouble("reorder")));
                v.add(rs.getString("rack"));
                

                dtm.addRow(v);

            }
            DefaultTableCellRenderer customRenderer = new DefaultTableCellRenderer() {
                @Override
                public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                    java.awt.Component cell = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                    DefaultTableModel model = (DefaultTableModel) table.getModel();
                    double reorder = Double.parseDouble(model.getValueAt(row, 5).toString().replace(",", ""));
                    double qty = Double.parseDouble(model.getValueAt(row, 4).toString().replace(",", ""));

                    // Set the foreground color for the entire row based on the condition
                    if (reorder > qty) {
                        cell.setForeground(Color.RED);
                    } else {
                        cell.setForeground(Color.BLACK);
                    }

                    // Right align specific columns
                    if (column == 3 || column == 4 || column == 5) {
                        setHorizontalAlignment(DefaultTableCellRenderer.RIGHT);
                    } else {
                        setHorizontalAlignment(DefaultTableCellRenderer.LEFT);
                    }

                    return cell;
                }
            };

            // Apply the custom renderer to all columns
            for (int i = 0; i < jTable1.getColumnCount(); i++) {
                jTable1.getColumnModel().getColumn(i).setCellRenderer(customRenderer);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    public void tbups() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            ResultSet rs = MC_DB.search_dataQuery("SELECT * FROM stock");
            NumberFormat numberFormat = new DecimalFormat("#,##0.00");
            while (rs.next()) {

                Vector v = new Vector();

                v.add(rs.getString("id"));
                v.add(rs.getString("code"));
                v.add(rs.getString("name"));
                v.add(numberFormat.format(rs.getDouble("sell_price")));
                v.add(numberFormat.format(rs.getDouble("qty")));
                v.add(numberFormat.format(rs.getDouble("reorder")));
                v.add(rs.getString("rack"));
                

                dtm.addRow(v);

            }
            DefaultTableCellRenderer customRenderer = new DefaultTableCellRenderer() {
                @Override
                public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                    java.awt.Component cell = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                    DefaultTableModel model = (DefaultTableModel) table.getModel();
                    double reorder = Double.parseDouble(model.getValueAt(row, 5).toString().replace(",", ""));
                    double qty = Double.parseDouble(model.getValueAt(row, 4).toString().replace(",", ""));

                    // Set the foreground color for the entire row based on the condition
                    if (reorder > qty) {
                        cell.setForeground(Color.RED);
                    } else {
                        cell.setForeground(Color.BLACK);
                    }

                    // Right align specific columns
                    if (column == 3 || column == 4 || column == 5) {
                        setHorizontalAlignment(DefaultTableCellRenderer.RIGHT);
                    } else {
                        setHorizontalAlignment(DefaultTableCellRenderer.LEFT);
                    }

                    return cell;
                }
            };

            // Apply the custom renderer to all columns
            for (int i = 0; i < jTable1.getColumnCount(); i++) {
                jTable1.getColumnModel().getColumn(i).setCellRenderer(customRenderer);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(product_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(product_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(product_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(product_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new product_list().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
