/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easypos;

import DB.MC_DB;
import static easypos.newCashier_test01.s_id;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author hello
 */
public class stock_more extends javax.swing.JFrame {

    /**
     * Creates new form stock_more
     */
    public stock_more() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        fillCategory();
        fillSubCategory();
        fillGroup();
        fillSize();
        AutoCompleteDecorator.decorate(combo_group);
        AutoCompleteDecorator.decorate(combo_cat_01);
        AutoCompleteDecorator.decorate(combo_cat_02);
        AutoCompleteDecorator.decorate(combo_cat_03);
        AutoCompleteDecorator.decorate(combo_sub_cat_01);
        AutoCompleteDecorator.decorate(combo_sub_cat_02);
        AutoCompleteDecorator.decorate(combo_sub_cat_03);
        AutoCompleteDecorator.decorate(combo_size);
        menu.add(jPanel7);
        short_down_product();
        product_teb();
        cat1_to_cat2();
        cat2_to_cat3();
        cat3_to_sub1();
        sub1_to_sub2();
        sub2_to_sub3();
        size_to_group();
        group_to_weight();
        sub3_to_color();
        clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        menu = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        myButton11 = new button.MyButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txt_code = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbl_sinhala_name = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        combo_cat_01 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        combo_cat_02 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        combo_cat_03 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        combo_sub_cat_01 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        combo_sub_cat_02 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        combo_sub_cat_03 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_color = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        combo_size = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        combo_group = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txt_weight = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_description = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_price_01 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_price_02 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_price_03 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        myButton7 = new button.MyButton();
        myButton8 = new button.MyButton();
        myButton9 = new button.MyButton();
        myButton10 = new button.MyButton();
        jPanel6 = new javax.swing.JPanel();
        myButton1 = new button.MyButton();
        myButton2 = new button.MyButton();
        myButton3 = new button.MyButton();
        myButton4 = new button.MyButton();
        myButton5 = new button.MyButton();
        myButton6 = new button.MyButton();
        jButton17 = new javax.swing.JButton();
        myButton12 = new button.MyButton();
        myButton13 = new button.MyButton();

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", ""
            }
        ));
        jTable3.setRowHeight(25);
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setMinWidth(0);
            jTable3.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable3.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable3.getColumnModel().getColumn(2).setMinWidth(200);
            jTable3.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTable3.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 120));

        menu.setFocusable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Name"
            }
        ));
        jTable1.setRowHeight(35);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        myButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-remove-40.png"))); // NOI18N
        myButton11.setText("Remove");
        myButton11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        myButton11.setRadius(9);
        myButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(myButton11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(myButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Code", "Name", "Sinhala", "Category 01", "Category 02", "Category 03", "Sub Category 01", "Sub Category 02", "Sub Category 03", "Colour", "Size", "Group", "Weight", "Description", "Price 01", "Price 02", "Price 03"
            }
        ));
        jTable2.setRowHeight(35);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(0);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable2.getColumnModel().getColumn(2).setMinWidth(200);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTable2.getColumnModel().getColumn(2).setMaxWidth(200);
            jTable2.getColumnModel().getColumn(3).setMinWidth(0);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(0);
            jTable2.getColumnModel().getColumn(3).setMaxWidth(0);
            jTable2.getColumnModel().getColumn(5).setMinWidth(0);
            jTable2.getColumnModel().getColumn(5).setPreferredWidth(0);
            jTable2.getColumnModel().getColumn(5).setMaxWidth(0);
            jTable2.getColumnModel().getColumn(6).setMinWidth(0);
            jTable2.getColumnModel().getColumn(6).setPreferredWidth(0);
            jTable2.getColumnModel().getColumn(6).setMaxWidth(0);
            jTable2.getColumnModel().getColumn(8).setMinWidth(0);
            jTable2.getColumnModel().getColumn(8).setPreferredWidth(0);
            jTable2.getColumnModel().getColumn(8).setMaxWidth(0);
            jTable2.getColumnModel().getColumn(9).setMinWidth(0);
            jTable2.getColumnModel().getColumn(9).setPreferredWidth(0);
            jTable2.getColumnModel().getColumn(9).setMaxWidth(0);
        }

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
            .addComponent(jTextField1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Product Code :");

        txt_code.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_codeKeyReleased(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Product Name :");

        lbl_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Sinhala Name :");

        lbl_sinhala_name.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Category 01 :");

        combo_cat_01.setEditable(true);
        combo_cat_01.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_cat_01.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Category 02 :");

        combo_cat_02.setEditable(true);
        combo_cat_02.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_cat_02.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Category 03 :");

        combo_cat_03.setEditable(true);
        combo_cat_03.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_cat_03.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Sub Category 01 :");

        combo_sub_cat_01.setEditable(true);
        combo_sub_cat_01.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_sub_cat_01.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Sub Category" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Sub Category 02 :");

        combo_sub_cat_02.setEditable(true);
        combo_sub_cat_02.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_sub_cat_02.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Sub Category" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Sub Category 03 :");

        combo_sub_cat_03.setEditable(true);
        combo_sub_cat_03.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_sub_cat_03.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Sub Category" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Colour :");

        txt_color.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_color.setToolTipText("");
        txt_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_colorActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Size :");

        combo_size.setEditable(true);
        combo_size.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_size.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Size" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Group :");

        combo_group.setEditable(true);
        combo_group.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_group.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Group" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Weight :");

        txt_weight.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_weight.setToolTipText("");
        txt_weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_weightActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Description :");

        txt_description.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_description.setToolTipText("");
        txt_description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descriptionActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Price 01** :");

        txt_price_01.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_price_01.setToolTipText("");
        txt_price_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_price_01ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Price  02** :");

        txt_price_02.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_price_02.setToolTipText("");
        txt_price_02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_price_02ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Price 03 **:");

        txt_price_03.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_price_03.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_code)
                    .addComponent(combo_cat_01, 0, 172, Short.MAX_VALUE)
                    .addComponent(combo_sub_cat_01, 0, 172, Short.MAX_VALUE)
                    .addComponent(txt_color)
                    .addComponent(txt_weight)
                    .addComponent(txt_price_02))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_cat_02, 0, 178, Short.MAX_VALUE)
                    .addComponent(combo_sub_cat_02, 0, 178, Short.MAX_VALUE)
                    .addComponent(combo_size, 0, 178, Short.MAX_VALUE)
                    .addComponent(txt_description)
                    .addComponent(txt_price_03))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_sinhala_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_cat_03, 0, 174, Short.MAX_VALUE)
                    .addComponent(combo_sub_cat_03, 0, 174, Short.MAX_VALUE)
                    .addComponent(combo_group, 0, 174, Short.MAX_VALUE)
                    .addComponent(txt_price_01))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_code, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_sinhala_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_cat_01, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_cat_02)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_cat_03))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_sub_cat_01, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_sub_cat_02)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_sub_cat_03))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_color, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_size)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_group))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_weight, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_description)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_price_01))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_price_02, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_price_03))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        myButton7.setForeground(new java.awt.Color(255, 255, 255));
        myButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-40.png"))); // NOI18N
        myButton7.setText("Add");
        myButton7.setColor(new java.awt.Color(0, 0, 102));
        myButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myButton7.setRadius(25);
        myButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton7ActionPerformed(evt);
            }
        });

        myButton8.setForeground(new java.awt.Color(255, 255, 255));
        myButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-edit-row-40.png"))); // NOI18N
        myButton8.setText("Edit");
        myButton8.setColor(new java.awt.Color(0, 0, 102));
        myButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myButton8.setRadius(25);
        myButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton8ActionPerformed(evt);
            }
        });

        myButton9.setForeground(new java.awt.Color(255, 255, 255));
        myButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-remove-40.png"))); // NOI18N
        myButton9.setText("Remove");
        myButton9.setColor(new java.awt.Color(0, 0, 102));
        myButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myButton9.setRadius(25);
        myButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton9ActionPerformed(evt);
            }
        });

        myButton10.setForeground(new java.awt.Color(255, 255, 255));
        myButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-clear-40.png"))); // NOI18N
        myButton10.setText("Clear");
        myButton10.setColor(new java.awt.Color(0, 0, 102));
        myButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myButton10.setRadius(25);
        myButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(myButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(myButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(myButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(myButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(myButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(myButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        myButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-product-30.png"))); // NOI18N
        myButton1.setText("Add Category");
        myButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myButton1.setRadius(9);
        myButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });

        myButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-defective-product-30.png"))); // NOI18N
        myButton2.setText("Remove Categoty");
        myButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myButton2.setRadius(9);
        myButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });

        myButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-to-shopping-basket-30.png"))); // NOI18N
        myButton3.setText("Add Sub Category");
        myButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myButton3.setRadius(9);
        myButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton3ActionPerformed(evt);
            }
        });

        myButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-food-receiver-30.png"))); // NOI18N
        myButton4.setText("Remove Sub Category");
        myButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myButton4.setRadius(9);
        myButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton4ActionPerformed(evt);
            }
        });

        myButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-group-30.png"))); // NOI18N
        myButton5.setText("Add Group");
        myButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myButton5.setRadius(9);
        myButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton5ActionPerformed(evt);
            }
        });

        myButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-minus-30.png"))); // NOI18N
        myButton6.setText("Remove Group");
        myButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myButton6.setRadius(9);
        myButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton6ActionPerformed(evt);
            }
        });

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-home-24.png"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        myButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-page-size-30.png"))); // NOI18N
        myButton12.setText("Add Size");
        myButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myButton12.setRadius(9);
        myButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton12ActionPerformed(evt);
            }
        });

        myButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-remove-bookmark-30.png"))); // NOI18N
        myButton13.setText("Remove Size");
        myButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myButton13.setRadius(9);
        myButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(myButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(myButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(myButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(myButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(myButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(myButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(myButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(myButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(myButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(myButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(myButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(myButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
            .addComponent(myButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(myButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void group_to_weight() {
        combo_group.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    txt_weight.grabFocus();
                }
            }
        });

    }

    public void size_to_group() {
        combo_size.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    combo_group.grabFocus();
                }
            }
        });

    }

    public void sub3_to_color() {
        combo_sub_cat_03.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    txt_color.grabFocus();
                }
            }
        });

    }

    public void sub2_to_sub3() {
        combo_sub_cat_02.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    combo_sub_cat_03.grabFocus();
                }
            }
        });

    }

    public void cat1_to_cat2() {
        combo_cat_01.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    combo_cat_02.grabFocus();
                }
            }
        });

    }

    public void cat2_to_cat3() {
        combo_cat_02.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    combo_cat_03.grabFocus();
                }
            }
        });

    }

    public void cat3_to_sub1() {
        combo_cat_03.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    combo_sub_cat_01.grabFocus();
                }
            }
        });

    }

    public void sub1_to_sub2() {
        combo_sub_cat_01.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    combo_sub_cat_02.grabFocus();
                }
            }
        });

    }

    public void product_teb() {
        jTable3.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent evt) {

                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

                    s_id = jTable3.getValueAt(jTable3.getSelectedRow(), 0).toString();

                    find_product(s_id);
                    combo_cat_01.grabFocus();
                    menu.setVisible(false);
                }
            }

        });

    }

    private void find_product(String s_id) {

        try {
            ResultSet rs = MC_DB.search_dataQuery("SELECT * FROM stock where id = '" + s_id + "' ");
            if (rs.next()) {
                txt_code.setText(rs.getString("code"));
                lbl_name.setText(rs.getString("name"));
                lbl_sinhala_name.setText(rs.getString("name2"));
                txt_price_01.setText(rs.getString("sell_price"));
                txt_price_02.setText(rs.getString("sell_price"));
                txt_price_03.setText(rs.getString("sell_price"));

            } else {
                txt_code.setText("");
                // jTextField2.setText("");
                lbl_name.setText("");
                lbl_sinhala_name.setText("");
                txt_price_01.setText("");
                txt_price_02.setText("");
                txt_price_03.setText("");

            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public void short_down_product() {
        txt_code.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                    jTable3.grabFocus();
                    jTable3.setRowSelectionInterval(0, 0);

                }
            }
        });

    }

    private void fillSize() {
        try {
            ResultSet rs = MC_DB.search_dataQuery("select * from size_details");

            while (rs.next()) {
                String barcode = rs.getString("category_name");
                combo_size.addItem(barcode);

            }
            if (combo_size.getItemCount() > 0) {
                combo_size.setSelectedIndex(0);
            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void fillCategory() {
        try {
            ResultSet rs = MC_DB.search_dataQuery("select * from category");

            while (rs.next()) {
                String barcode = rs.getString("category_name");
                combo_cat_01.addItem(barcode);
                combo_cat_02.addItem(barcode);
                combo_cat_03.addItem(barcode);
            }
            if (combo_cat_01.getItemCount() > 0) {
                combo_cat_01.setSelectedIndex(0);
            }
            if (combo_cat_02.getItemCount() > 0) {
                combo_cat_02.setSelectedIndex(0);
            }
            if (combo_cat_03.getItemCount() > 0) {
                combo_cat_03.setSelectedIndex(0);
            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void fillGroup() {
        try {
            ResultSet rs = MC_DB.search_dataQuery("select * from group_details");

            while (rs.next()) {
                String barcode = rs.getString("category_name");
                combo_group.addItem(barcode);
            }

            if (combo_group.getItemCount() > 0) {
                combo_group.setSelectedIndex(0);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void fillSubCategory() {
        try {
            ResultSet rs = MC_DB.search_dataQuery("select * from sub_category");

            while (rs.next()) {
                String barcode = rs.getString("category_name");
                combo_sub_cat_01.addItem(barcode);
                combo_sub_cat_02.addItem(barcode);
                combo_sub_cat_03.addItem(barcode);
            }

            if (combo_sub_cat_01.getItemCount() > 0) {
                combo_sub_cat_01.setSelectedIndex(0);
            }
            if (combo_sub_cat_02.getItemCount() > 0) {
                combo_sub_cat_02.setSelectedIndex(0);
            }
            if (combo_sub_cat_03.getItemCount() > 0) {
                combo_sub_cat_03.setSelectedIndex(0);
            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        new Dashboard_001().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton17ActionPerformed
    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        tb_clear();
        new add_category().setVisible(true);
    }//GEN-LAST:event_myButton1ActionPerformed

    public void tbups_cat() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            ResultSet rs = MC_DB.search_dataQuery("SELECT * FROM category");
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("id"));
                v.add(rs.getString("category_name"));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }

    public void tbups_subCat() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            ResultSet rs = MC_DB.search_dataQuery("SELECT * FROM sub_category");
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("id"));
                v.add(rs.getString("category_name"));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }

    public void tbups_group() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            ResultSet rs = MC_DB.search_dataQuery("SELECT * FROM group_details");
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("id"));
                v.add(rs.getString("category_name"));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }

    public void tbups_size() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            ResultSet rs = MC_DB.search_dataQuery("SELECT * FROM size_details");
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("id"));
                v.add(rs.getString("category_name"));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }

    String s_type = "";
    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        s_type = "Category";
        tbups_cat();
    }//GEN-LAST:event_myButton2ActionPerformed

    private void myButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton11ActionPerformed
        System.out.println(s_type
        );
        String id = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        if (s_type.equals("Category")) {
            MC_DB.insert_data("DELETE FROM category WHERE id = '" + id + "'");
            tbups_cat();
        } else if (s_type.equals("SubCategory")) {
            MC_DB.insert_data("DELETE FROM sub_category WHERE id = '" + id + "'");
            tbups_subCat();
        } else if (s_type.equals("Group")) {
            MC_DB.insert_data("DELETE FROM sub_category WHERE id = '" + id + "'");
            tbups_group();
        } else if (s_type.equals("Size")) {
            MC_DB.insert_data("DELETE FROM size_details WHERE id = '" + id + "'");
            tbups_size();
        }


    }//GEN-LAST:event_myButton11ActionPerformed

    private void myButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton4ActionPerformed
        s_type = "SubCategory";
        tbups_subCat();
    }//GEN-LAST:event_myButton4ActionPerformed

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
        tb_clear();
        new add_sub_category().setVisible(true);
    }//GEN-LAST:event_myButton3ActionPerformed

    private void myButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton6ActionPerformed
        s_type = "Group";
        tbups_group();
    }//GEN-LAST:event_myButton6ActionPerformed

    private void myButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton5ActionPerformed
        tb_clear();
        new add_group().setVisible(true);
    }//GEN-LAST:event_myButton5ActionPerformed

    private void myButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton12ActionPerformed
        tb_clear();
        new add_size().setVisible(true);
    }//GEN-LAST:event_myButton12ActionPerformed

    private void myButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton13ActionPerformed
        s_type = "Size";
        tbups_size();
    }//GEN-LAST:event_myButton13ActionPerformed

    private void txt_codeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codeKeyReleased
        if (txt_code.getText().isEmpty()) {
            menu.setVisible(false);
        } else {

            menu.show(txt_code, 0, txt_code.getHeight());

            String key = txt_code.getText().trim() + "%";
            try {
                DefaultTableModel dtm = (DefaultTableModel) jTable3.getModel();
                dtm.setRowCount(0);
                ResultSet rs = MC_DB.search_dataQuery("SELECT * FROM stock WHERE code like '" + key + "' or name like '" + key + "' ");
                while (rs.next()) {

                    Vector v = new Vector();

                    v.add(rs.getString("id"));
                    v.add(rs.getString("code"));
                    v.add(rs.getString("name"));
                    v.add(rs.getString("sell_price"));

                    dtm.addRow(v);

                }

            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    MC_DB.myConnection().close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
//     jTextField2.grabFocus();
            menu.setVisible(false);

        }
    }//GEN-LAST:event_txt_codeKeyReleased

    private void txt_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_colorActionPerformed
        combo_size.grabFocus();
    }//GEN-LAST:event_txt_colorActionPerformed

    private void txt_weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_weightActionPerformed
        txt_description.grabFocus();
    }//GEN-LAST:event_txt_weightActionPerformed

    private void txt_descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descriptionActionPerformed
        txt_price_01.grabFocus();
    }//GEN-LAST:event_txt_descriptionActionPerformed

    private void txt_price_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_price_01ActionPerformed
        txt_price_02.grabFocus();
    }//GEN-LAST:event_txt_price_01ActionPerformed

    private void txt_price_02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_price_02ActionPerformed
        txt_price_03.grabFocus();
    }//GEN-LAST:event_txt_price_02ActionPerformed

    String s_id, s_code, s_name, s_sinhala, s_cat1, s_cat2, s_cat3, s_sub1, s_sub2, s_sub3,
            s_color, s_size, s_group, s_weight, s_description, s_data, s_colomn;
    double d_price1, d_price2, d_price3;

    private void myButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton7ActionPerformed

        s_code = txt_code.getText().trim();
        s_name = lbl_name.getText().trim();
        s_sinhala = lbl_sinhala_name.getText().trim();
        s_cat1 = combo_cat_01.getSelectedItem().toString();
        s_cat2 = combo_cat_02.getSelectedItem().toString();
        s_cat3 = combo_cat_03.getSelectedItem().toString();
        s_sub1 = combo_sub_cat_01.getSelectedItem().toString();
        s_sub2 = combo_sub_cat_02.getSelectedItem().toString();
        s_sub3 = combo_sub_cat_03.getSelectedItem().toString();
        s_color = txt_color.getText().trim();
        s_size = combo_size.getSelectedItem().toString();
        s_group = combo_group.getSelectedItem().toString();
        s_weight = txt_weight.getText().trim();
        s_description = txt_description.getText().trim();
        d_price1 = Double.parseDouble(txt_price_01.getText().trim());
        d_price2 = Double.parseDouble(txt_price_02.getText().trim());
        d_price3 = Double.parseDouble(txt_price_03.getText().trim());

        s_data = " '" + s_id + "','" + s_code + "','" + s_name + "','" + s_sinhala + "',"
                + "'" + s_cat1 + "','" + s_cat2 + "','" + s_cat3 + "','" + s_sub1 + "',"
                + "'" + s_sub2 + "','" + s_sub3 + "','" + s_color + "','" + s_size + "',"
                + "'" + s_group + "','" + s_weight + "','" + s_description + "','" + d_price1 + "',"
                + "'" + d_price2 + "','" + d_price3 + "' ";

        s_colomn = "id,code,name,sinhala,cat1,cat2,cat3,subcat1,subcat2,subcat3,colorx,sizex,groupx,weightx,description,price1,price2,price3";

        MC_DB.add_data_WithColumns("stock_more", s_colomn, s_data);

        JOptionPane.showMessageDialog(this, MC_DB.s_message);
    }//GEN-LAST:event_myButton7ActionPerformed

    private void myButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton8ActionPerformed
        s_id = jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString();
        s_code = txt_code.getText().trim();
        s_name = lbl_name.getText().trim();
        s_sinhala = lbl_sinhala_name.getText().trim();
        s_cat1 = combo_cat_01.getSelectedItem().toString();
        s_cat2 = combo_cat_02.getSelectedItem().toString();
        s_cat3 = combo_cat_03.getSelectedItem().toString();
        s_sub1 = combo_sub_cat_01.getSelectedItem().toString();
        s_sub2 = combo_sub_cat_02.getSelectedItem().toString();
        s_sub3 = combo_sub_cat_03.getSelectedItem().toString();
        s_color = txt_color.getText().trim();
        s_size = combo_size.getSelectedItem().toString();
        s_group = combo_group.getSelectedItem().toString();
        s_weight = txt_weight.getText().trim();
        s_description = txt_description.getText().trim();
        d_price1 = Double.parseDouble(txt_price_01.getText().trim());
        d_price2 = Double.parseDouble(txt_price_02.getText().trim());
        d_price3 = Double.parseDouble(txt_price_03.getText().trim());

        MC_DB.insert_data("UPDATE stock_more SET code = '" + s_code + "',name = '" + s_name + "',"
                + "sinhala = '" + s_sinhala + "',cat1 = '" + s_cat1 + "',cat2 = '" + s_cat2 + "',"
                + "cat3 = '" + s_cat3 + "',subcat1 = '" + s_sub1 + "',subcat2 = '" + s_sub2 + "',"
                + "subcat3 = '" + s_sub3 + "',colorx = '" + s_color + "',sizex = '" + s_size + "',"
                + "groupx = '" + s_group + "',weightx = '" + s_weight + "',description = '" + s_description + "',"
                + "price1 = '" + d_price1 + "',price2 = '" + d_price2 + "',price3 = '" + d_price3 + "' WHERE id  = '" + s_id + "'");
        JOptionPane.showMessageDialog(this, MC_DB.s_message);
        clear();
    }//GEN-LAST:event_myButton8ActionPerformed

    private void myButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton10ActionPerformed
        clear();
    }//GEN-LAST:event_myButton10ActionPerformed

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        s_id = jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString();
        set_details(s_id);


    }//GEN-LAST:event_jTable2MousePressed

    private void myButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton9ActionPerformed
        s_id = jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString();
        MC_DB.insert_data("DELETE FROM stock_more WHERE id = '" + s_id + "'");
        JOptionPane.showMessageDialog(this, MC_DB.s_message);
        clear();
    }//GEN-LAST:event_myButton9ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        String key = "%" + jTextField1.getText().trim() + "%";
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            dtm.setRowCount(0);
            ResultSet rs = MC_DB.search_dataQuery("SELECT * FROM stock_more WHERE "
                    + "code LIKE '" + key + "' || name LIKE '" + key + "' || cat1 LIKE '" + key + "' ||"
                    + " cat2 LIKE '" + key + "' || cat3 LIKE '" + key + "' || subcat1 LIKE '" + key + "' ||"
                    + " subcat2 LIKE '" + key + "' || subcat3 LIKE '" + key + "' || colorx LIKE '" + key + "' ||"
                    + " sizex LIKE '" + key + "' || groupx LIKE '" + key + "' || description LIKE '" + key + "' ");
            NumberFormat numberFormat = new DecimalFormat("#,##0.00");
            while (rs.next()) {

                Vector v = new Vector();

                v.add(rs.getString("id"));
                v.add(rs.getString("code"));
                v.add(rs.getString("name"));
                v.add(rs.getString("sinhala"));
                v.add(rs.getString("cat1"));
                v.add(rs.getString("cat2"));
                v.add(rs.getString("cat3"));
                v.add(rs.getString("subcat1"));
                v.add(rs.getString("subcat2"));
                v.add(rs.getString("subcat3"));
                v.add(rs.getString("colorx"));
                v.add(rs.getString("sizex"));
                v.add(rs.getString("groupx"));
                v.add(rs.getString("weightx"));
                v.add(rs.getString("description"));
                v.add(numberFormat.format(rs.getDouble("price1")));
                v.add(numberFormat.format(rs.getDouble("price2")));
                v.add(numberFormat.format(rs.getDouble("price3")));
                dtm.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    public void tbups() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            dtm.setRowCount(0);
            ResultSet rs = MC_DB.search_dataQuery("SELECT * FROM stock_more");
            NumberFormat numberFormat = new DecimalFormat("#,##0.00");
            while (rs.next()) {

                Vector v = new Vector();

                v.add(rs.getString("id"));
                v.add(rs.getString("code"));
                v.add(rs.getString("name"));
                v.add(rs.getString("sinhala"));
                v.add(rs.getString("cat1"));
                v.add(rs.getString("cat2"));
                v.add(rs.getString("cat3"));
                v.add(rs.getString("subcat1"));
                v.add(rs.getString("subcat2"));
                v.add(rs.getString("subcat3"));
                v.add(rs.getString("colorx"));
                v.add(rs.getString("sizex"));
                v.add(rs.getString("groupx"));
                v.add(rs.getString("weightx"));
                v.add(rs.getString("description"));
                v.add(numberFormat.format(rs.getDouble("price1")));
                v.add(numberFormat.format(rs.getDouble("price2")));
                v.add(numberFormat.format(rs.getDouble("price3")));
                dtm.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stock_more.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stock_more.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stock_more.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stock_more.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stock_more().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_cat_01;
    private javax.swing.JComboBox<String> combo_cat_02;
    private javax.swing.JComboBox<String> combo_cat_03;
    private javax.swing.JComboBox<String> combo_group;
    private javax.swing.JComboBox<String> combo_size;
    private javax.swing.JComboBox<String> combo_sub_cat_01;
    private javax.swing.JComboBox<String> combo_sub_cat_02;
    private javax.swing.JComboBox<String> combo_sub_cat_03;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_sinhala_name;
    private javax.swing.JPopupMenu menu;
    private button.MyButton myButton1;
    private button.MyButton myButton10;
    private button.MyButton myButton11;
    private button.MyButton myButton12;
    private button.MyButton myButton13;
    private button.MyButton myButton2;
    private button.MyButton myButton3;
    private button.MyButton myButton4;
    private button.MyButton myButton5;
    private button.MyButton myButton6;
    private button.MyButton myButton7;
    private button.MyButton myButton8;
    private button.MyButton myButton9;
    private javax.swing.JTextField txt_code;
    private javax.swing.JTextField txt_color;
    private javax.swing.JTextField txt_description;
    private javax.swing.JTextField txt_price_01;
    private javax.swing.JTextField txt_price_02;
    private javax.swing.JTextField txt_price_03;
    private javax.swing.JTextField txt_weight;
    // End of variables declaration//GEN-END:variables

    private void tb_clear() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
    }

    private void clear() {
        s_id = "";
        txt_code.setText("");
        txt_color.setText("");
        txt_description.setText("");
        txt_price_01.setText("");
        txt_price_02.setText("");
        txt_price_03.setText("");
        lbl_name.setText("");
        lbl_sinhala_name.setText("");
        combo_cat_01.setSelectedIndex(0);
        combo_cat_02.setSelectedIndex(0);
        combo_cat_03.setSelectedIndex(0);
        combo_size.setSelectedIndex(0);
        combo_sub_cat_01.setSelectedIndex(0);
        combo_sub_cat_02.setSelectedIndex(0);
        combo_sub_cat_03.setSelectedIndex(0);
        combo_group.setSelectedIndex(0);
        tbups();
    }

    private void set_details(String s_idx) {
        try {
            ResultSet rs_stock_more = MC_DB.search_dataQuery("SELECT * FROM stock_more WHERE id = '" + s_idx + "'");
            if (rs_stock_more.next()) {

                s_code = rs_stock_more.getString("code");
                s_cat1 = rs_stock_more.getString("cat1");
                s_cat2 = rs_stock_more.getString("cat2");
                s_cat3 = rs_stock_more.getString("cat3");
                s_color = rs_stock_more.getString("colorx");
                s_description = rs_stock_more.getString("description");
                s_group = rs_stock_more.getString("groupx");
                s_name = rs_stock_more.getString("name");
                s_sinhala = rs_stock_more.getString("sinhala");
                s_size = rs_stock_more.getString("sizex");
                s_sub1 = rs_stock_more.getString("subcat1");
                s_sub2 = rs_stock_more.getString("subcat2");
                s_sub3 = rs_stock_more.getString("subcat3");
                s_weight = rs_stock_more.getString("weightx");
                d_price1 = rs_stock_more.getDouble("price1");
                d_price2 = rs_stock_more.getDouble("price2");
                d_price3 = rs_stock_more.getDouble("price3");

                txt_code.setText(s_code);
                txt_color.setText(s_color);
                txt_description.setText(s_description);
                txt_price_01.setText(String.valueOf(d_price1));
                txt_price_02.setText(String.valueOf(d_price2));
                txt_price_03.setText(String.valueOf(d_price3));
                txt_weight.setText(s_weight);
                lbl_name.setText(s_name);
                lbl_sinhala_name.setText(s_sinhala);
                combo_cat_01.setSelectedItem(s_cat1);
                combo_cat_02.setSelectedItem(s_cat2);
                combo_cat_03.setSelectedItem(s_cat3);
                combo_sub_cat_01.setSelectedItem(s_sub1);
                combo_sub_cat_02.setSelectedItem(s_sub2);
                combo_sub_cat_03.setSelectedItem(s_sub3);
                combo_group.setSelectedItem(s_group);
                combo_size.setSelectedItem(s_size);

            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                MC_DB.myConnection().close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
}
